[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

  
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

